---
- name: Setup Chat App Server
  hosts: chat_server
  become: yes

  tasks:
    - name: Install Node.js and Nginx using dnf5
      ansible.builtin.dnf:
        name:
          - nginx
          - nodejs
        state: present
        use_backend: dnf5

    - name: Enable and start Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
