---
- name: Setup Chat App Server (Manual Node.js install)
  hosts: chat_server
  become: yes

  tasks:

    - name: Enable nginx1 via amazon-linux-extras
      ansible.builtin.command: amazon-linux-extras enable nginx1

    - name: Clean yum metadata
      ansible.builtin.command: yum clean metadata

    - name: Install Nginx via dnf with dnf5 backend
      ansible.builtin.dnf:
        name: nginx
        state: present
        use_backend: dnf5

    - name: Install Node.js 18 from NodeSource (shell)
      ansible.builtin.shell: |
        curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
        dnf install -y nodejs
      args:
        executable: /bin/bash

    - name: Enable and start Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
