---
- name: Setup Chat App Server
  hosts: chat_server
  become: yes

  tasks:

    - name: Install EPEL repository
      ansible.builtin.yum:
        name: epel-release
        state: present

    - name: Install Node.js and Nginx
      ansible.builtin.yum:
        name:
          - nginx
          - nodejs
        state: present

    - name: Enable and start Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
