---
- name: Setup Chat App Server
  hosts: chat_server
  become: yes

  tasks:

    - name: Enable nginx via amazon-linux-extras
      ansible.builtin.command: amazon-linux-extras enable nginx1

    - name: Enable nodejs via amazon-linux-extras
      ansible.builtin.command: amazon-linux-extras enable nodejs16

    - name: Clean yum metadata
      ansible.builtin.command: yum clean metadata

    - name: Install Node.js and Nginx via yum
      ansible.builtin.yum:
        name:
          - nginx
          - nodejs
        state: present

    - name: Enable and start Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
