---
- name: Setup Chat App Server (Node.js 16 - Amazon Linux 2)
  hosts: chat_server
  become: yes

  tasks:

    - name: Enable nginx1 via amazon-linux-extras
      ansible.builtin.shell: amazon-linux-extras enable nginx1
      args:
        executable: /bin/bash

    - name: Clean yum metadata
      ansible.builtin.shell: yum clean metadata
      args:
        executable: /bin/bash

    - name: Install Nginx
      ansible.builtin.shell: yum install -y nginx
      args:
        executable: /bin/bash

    - name: Install Node.js 16 from NodeSource (safe glibc 2.26 compatible)
      ansible.builtin.shell: |
        curl -fsSL https://rpm.nodesource.com/setup_16.x | bash -
        while fuser /var/run/yum.pid >/dev/null 2>&1; do
          echo "Waiting for yum lock..."; sleep 3;
        done
        yum install -y nodejs
      args:
        executable: /bin/bash

    - name: Enable and start Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
