---
- name: Setup Chat App Server
  hosts: chat_server
  become: yes

  tasks:

    - name: Install Nginx and Node.js using raw shell
      ansible.builtin.shell: |
        yum install -y nginx
        curl -sL https://rpm.nodesource.com/setup_18.x | bash -
        yum install -y nodejs

    - name: Enable and start Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
